# .github/workflows/pyavater.yml
name: Run Python Script

on: 
  push:  # プッシュイベントでトリガー
    branches:
      - main  # mainブランチにプッシュされたときに実行

jobs:
  run-script:
    runs-on: ubuntu-latest  # 実行環境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # コードをチェックアウト

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 使用するPythonのバージョン

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py
          # 必要なパッケージがあればここに追加
          # pip install -r requirements.txt

      - name: Run script
        run: python bot.py  # Pythonスクリプトを実行
